<?php

include_once 'setting.inc.php';

$_lang['collegedocs'] = 'Документы колледжа';
$_lang['collegedocs_menu_desc'] = 'сведения об организации';
$_lang['collegedocs_intro_msg'] = 'Управление документами, размещаемыми в разделе сведения об образовательной организации';
$_lang['collegedocs_items'] = 'Файлы и ссылки';
$_lang['collegedocs_item_id'] = 'Id';
$_lang['collegedocs_item_name'] = 'Имя файла';
$_lang['collegedocs_item_description'] = 'Описание';
$_lang['collegedocs_item_active'] = 'Активно';
$_lang['collegedocs_item_resource_id'] = 'Id страницы';
$_lang['collegedocs_item_resource'] = 'Раздел';
$_lang['collegedocs_item_url'] = 'Адрес ссылки';
$_lang['collegedocs_item_load_name'] = 'Название на странице';
$_lang['collegedocs_item_filetype'] = 'Тип файла';
$_lang['collegedocs_item_catpath'] = 'Путь к файлу';
$_lang['collegedocs_item_itemtype'] = 'Тип элемента';
$_lang['collegedocs_item_pagetitle'] = 'Раздел';
$_lang['collegedocs_item_doctype'] = 'Тип документа';
$_lang['collegedocs_item_choose_doctype'] = 'Выберите тип документа';
$_lang['collegedocs_item_create'] = 'Добавить файл или ссылку';
$_lang['collegedocs_item_update'] = 'Изменить файл и описание';
$_lang['collegedocs_item_link_update'] = 'Изменить ссылку и описание';
$_lang['collegedocs_item_choose_resource'] = 'Выберите раздел';
$_lang['collegedocs_item_file_upload'] = 'Выберите файл для загрузки';
$_lang['collegedocs_item_file_create'] = 'Добавить файл';
$_lang['collegedocs_item_url_create'] = 'Добавить ссылку';
$_lang['collegedocs_item_enable'] = 'Показывать на сайте';
$_lang['collegedocs_items_enable'] = 'Показывать элементы на сайте';
$_lang['collegedocs_item_disable'] = 'Отключить показ на сайте';
$_lang['collegedocs_items_disable'] = 'Отключить показ элементов на сайте';
$_lang['collegedocs_item_remove'] = 'Удалить файл и ссылку документа';
$_lang['collegedocs_items_remove'] = 'Удалить файлы/ссылки для документов';
$_lang['collegedocs_item_remove_confirm'] = 'Вы уверены, что хотите удалить запись о файле/ссылке для раздела?';
$_lang['collegedocs_items_remove_confirm'] = 'Вы уверены, что хотите удалить все жти записи о файлах/ссылках?';
$_lang['collegedocs_item_active'] = 'Включено';

$_lang['collegedocs_item_err_name'] = 'Вы должны указать название.';
$_lang['collegedocs_item_err_ae'] = 'Запись с таким именем уже существует.';
$_lang['collegedocs_item_err_nf'] = 'Файл не найден.';
$_lang['collegedocs_item_err_ns'] = 'Файл/ссылка не указаны.';
$_lang['collegedocs_item_err_remove'] = 'Ошибка при удалении записи.';
$_lang['collegedocs_item_err_save'] = 'Ошибка при сохранении записи.';
$_lang['collegedocs_grid_search'] = 'Поиск';
$_lang['collegedocs_grid_actions'] = 'Действия';
$_lang['collegedocs_grid_actions'] = 'Действия';
$_lang['collegedocs_item_err_resource_id'] = 'Не выбрана категория';
$_lang['collegedocs_item_err_itemtype'] = 'Не определен тип записи (файл/ссылка)';
$_lang['collegedocs_item_err_path'] = 'Отсутствует путь к файлу';
$_lang['collegedocs_item_err_is'] = '';
$_lang['collegedocs_item_file_err_save'] = 'Ошибка при сохранении файла';
$_lang['collegedocs_item_files_err_nosource'] = 'Не указан медиа источник в настройках пакета';